### ISSUE TITLE
Colocar no site o evento da comunidade de 03/05/2024

### ISSUE THREAD

**Issue by digidweb** [rubyonrio/rubyonrio.github.com#102]
Atualizar a agenda de eventos da comunidade no site, colocando a imagem (ou hora, data e local) e a descrição: **Uma oficina pra você aprender a criar a sua própria Ruby Gem!**
Aprenda a criar programas e funcionalidades reutilizáveis em qualquer projeto Ruby.
Também criaremos uma CLI (Interface de Linha de Comando) pra usar o seu programa.
Traga o seu laptop e aprenda fazendo!

![divulgacaoMeetupRubyOnRio](https://github.com/rubyonrio/rubyonrio.github.com/assets/92958088/f5fe6960-a90e-4002-8924-6c6627190d09)

**Comment by giovannism20** [comment]
Acredito que podemos fechar essa issue @digidweb
