### ISSUE TITLE
Comentários com disqus nos posts

### ISSUE THREAD

**Issue by lucianosousa** [rubyonrio/rubyonrio.github.com#18]
https://disqus.com/

**Comment by lucianosousa** [comment]
@cefigueiredo @tauil como ficou isso?

**Comment by tauil** [comment]
Até onde sei. Nada mudou. Só acho válido implementar se formos voltar com a ideia de fazer posts.

**Comment by lucianosousa** [comment]
faremos

**Comment by tauil** [comment]
Ok.
